backend:
  name: git-gateway
  branch: main

collections:
  - name: blog
    label: Blog
    folder: src/content/blog
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {label: "Draft", name: "draft", widget: "boolean", default: true}

media_folder: public/img
public_folder: /img