backend:
  name: github
  repo: sample-sg

collections:
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

media_folder: public/img
public_folder: /img