backend:
  name: github
  repo: sample-sg
  branch: main
  site_domain: fujibayashi-ast.github.io
  base_url: https://fujibayashi-ast.github.io/sample-sg/
  auth_endpoint: api/auth
  auth_scope: repo
  app_id: Ov23liWxApOFcYtrMmkj

collections:
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

media_folder: public/img
public_folder: /img